### ISSUE TITLE
Windows Defender에서 바이러스로 인식 (Windows 10)

### ISSUE THREAD

**Issue by caoko** [teamnop/HPuTTY#11]
![image](https://cloud.githubusercontent.com/assets/19994110/16366511/6490124a-3c53-11e6-8e5b-fbb75664f7cf.png)

위 화면과 같이 바이러스로 인식되는 문제가 있습니다.
여기 Release 페이지에서 다운 받은 installer로 다시 설치하고 검사했을 때는
Windows Defender가 바이러스로 인식하지 않더군요.
현상을 이해할 수 없습니다.
아마 Windows Defender의 예전 정의 중에 바이러스로 인식하는 부분이 있었나 봅니다.
최신 정의는 인식하지 않는 듯...

**Comment by noricube** [comment]
안녕하세요.
제보해주셔서 저도 테스트 해보니 다운 받으면 무조건 바이러스로 인식 되네요.

혹시나 해서 VirusTotal로 검사 해보았는데 오진이라고 생각 되네요.
https://www.virustotal.com/ko/file/21079af97fd061be85b24cd944160b68a6972cbc51220dd73be6fd173f639a3e/analysis/

우선 MS에 오진이라고 알려둔 상태입니다. 내용 업데이트 되면 여기에도 알려드리겠습니다.

**Comment by noricube** [comment]
몇가지 업데이트도 할겸 오진도 피할겸 `p0.66-t027-h004` 버전을 릴리즈 하였습니다.
이 버전으로 받으시면 문제가 없을듯 하네요.

**Comment by caoko** [comment]
빠른 처리 감사합니다.
잘 사용하고 있습니다. ^^

**Comment by noricube** [comment]
MS에서 오진 되는것 해결 되었다고 메일 받았습니다.
실제로 확인해보니 해결 되었네요.
