### ISSUE TITLE
VS2012에서는 빌드가 불가능한지 문의.

### ISSUE THREAD

**Issue by bluems** [teamnop/HPuTTY#4]
VS2012에서 window.c 파일에서 아래 구문 에러가 발생하는데 2015 및 이후 IDE에서만 빌드가 되는 것인지 문의.

> ....\window.c(698): error C2143: 구문 오류 : ';'이(가) '형식' 앞에 없습니다.
> 1>....\window.c(807): error C2275: 'Filename' : 이 형식을 식으로 잘못 사용했습니다.
> 1>          hputty-master\hputty-master\misc.h(21) : 'Filename' 선언을 참조하십시오.
> 1>....\window.c(807): error C2065: 'win_icon' : 선언되지 않은 식별자입니다.
> 1>....\window.c(808): error C2065: 'win_icon' : 선언되지 않은 식별자입니다.
> 1>....\window.c(809): error C2065: 'win_icon' : 선언되지 않은 식별자입니다.
> 1>....\window.c(810): error C2065: 'win_icon' : 선언되지 않은 식별자입니다.

**Comment by noricube** [comment]
음.. VS2012에서 빌드가 불가능한지 몰랐네요.
테스트 해보고 다시 댓글 달아드리도록 하겠습니다.

**Comment by noricube** [comment]
직접 테스트해보니 VS2012에서 코드를 빌드하려면 몇가지 수정을 해야하네요.
수정할까 하였으나 hputty가 upstream으로 따르고 있는 puttytray도 VS2015만 지원하는것 같아서 VS2012 지원은 조금 힘들 것 같습니다.

가능하시다면 VS2015 설치 후 컴파일 하시는걸 추천드립니다.
