### ISSUE TITLE
버그: 설정->창->모양새 Allow selection of variable-pitch fonts

### ISSUE THREAD

**Issue by olambdao** [teamnop/HPuTTY#7]
Allow selection of variable-pitch fonts 옵션에 버그가 있습니다.

활성화가 되지 않습니다.

**Comment by noricube** [comment]
putty 최신버전에서도 작동하지 않네요. 수정할 수 있으면 수정해보겠습니다.

**Comment by noricube** [comment]
가변폭 글꼴을 선택하게 하는 옵션입니다.
이 옵션을 체크하고 가변폭 글꼴을 선택하면 적용됩니다.
